Day_3/django_project/books/urls.py
from django.urls import path
from .views import BookDetailView, BookListView

app_name = "books"
urlpatterns = [
    path("", BookListView.as_view(), name="book_list"),
    path("<slug:slug>/", BookDetailView.as_view(), name="book_detail"),
]

Day_3/django_project/django_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("pages.urls")),
    path("books/", include("books.urls")),
]

Day_3/django_project/pages/urls.py
from django.urls import path

from .views import HomePageView

app_name = "pages"
urlpatterns = [
    path("", HomePageView.as_view(), name="home")
]

Day_3/django_project/books/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse

# Create your models here.

class Book(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    author = models.CharField(max_length=255)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("books:book_detail", kwargs={"slug": self.slug})

Day_3/django_project/pages/models.py
from django.db import models

# Create your models here.

Day_3/django_project/books/views.py
from django.views.generic import DetailView, ListView
from .models import Book

# Create your views here.


class BookListView(ListView):
    model = Book
    context_object_name = "books"
    template_name = "books/list.html"


class BookDetailView(DetailView):
    model = Book
    context_object_name = "book"
    template_name = "books/detail.html"

Day_3/django_project/pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.

class HomePageView(TemplateView):
    template_name = "pages/home.html"

Day_3/django_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Project</title>
</head>
<body>
    {% block content %}
    {% endblock content %}
</body>
</html>

Day_3/django_project/templates/books/detail.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ book.title }} </h1>

    <ul>
        <li>Author: {{ book.author }}</li>
        
        <li>Created: {{ book.created_at }}</li>
        <li>Updated: {{ book.updated_at }}</li>
    </ul>

    <h2>Description</h2>
    <p> {{ book.description }}</p>
    <br><br>

    <p><a href="{% url "books:book_list" %}">Book List</a></p>
    
{% endblock content %}

Day_3/django_project/templates/books/list.html
{% extends "base.html" %}

{% block content %}
    <h1>Books</h1>
    <ul>
        {% for book in books %}
            <li><a href="{{ book.get_absolute_url }}"> {{ book }} </a></li>
        {% endfor %}
    </ul>
    <br><br>

    <p><a href="{% url "pages:home" %}">Pages Home</a></p>

{% endblock content %}

Day_3/django_project/templates/pages/home.html
{% extends "base.html" %}

{% block content %}
    <h1>Home page</h1>
    <i>Hello students!</i>
    <br><br>

    <p><a href="{% url "books:book_list" %}"> Book List</a></p>
{% endblock content %}